#!/usr/bin/env bash
set -euo pipefail

cp /autograder/submission/* /autograder/source

cd /autograder/source

# If you add dependencies later, uncomment:
# pip install -r requirements.txt

python3 autograde.py